### PR TITLE
Re-enable checking out of repo prior to running action

### PR DESCRIPTION
**Pull request by teepsdonnelly**
This pull request enables logging in with social accounts, however introduces technical debt due to requirements on how quickly we need to ship the feature.

[DEBT_ISSUE_TITLE] EXAMPLE ISSUE - Refactor logging in with social accounts

[DEBT_ISSUE_BODY] Currently, the logic for logging in with social accounts is at the view layer in the app. It needs to be moved out into a helper class and we should utilize the ViewModel appropriately to give the View what it needs. Let's keep our views as dumb as possible for readability and maintainability.

### CODE REVIEW

**Comment by shayfrendt** [comment]
🤔 Oooh what if issue `#3` cross-referenced back to this issue in its OP? That way there'd be a traceability story?

**Comment by teepsdonnelly** [comment]
> 🤔 Oooh what if issue `#3` cross-referenced back to this issue in its OP? That way there'd be a traceability story?

That's a great idea. I'll see what I can do :)

**Comment by teepsdonnelly** [comment]
> 🤔 Oooh what if issue `#3` cross-referenced back to this issue in its OP? That way there'd be a traceability story?

So I dug in a bit and I'm curious if it would be a misuse of the "Linked issues" and "Linked pull requests" feature if I used it here, since the purpose of those seems to be auto closing of issues linked to a PR at merge.

Given that we're only creating the issue AFTER a PR is merged (tech debt), would it be more pragmatic to just include a link to the original PR in the body of the newly created Issue?

Thoughts?

**Comment by shayfrendt** [comment]
Yeah so there's not technically support for "non-closing" issue references just yet within the issue and pull request linking feature. But as you can tell in this scenario, it'd be pretty sweet if that support existed. 😊 

>would it be more pragmatic to just include a link to the original PR in the body of the newly created Issue?

Probably for now I'd say yeah maybe this is the best workaround?

**Pull request merged**
